
name: CI-CD-Docker-Bot
env:
  PROJECT_NAME: "training_tracker_bot"

on:
  push:
    branches:
      - main

jobs:

   Delivery_to_server:
      runs-on: ubuntu-latest
      steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: ls
        uses: ls -la
        
      - name: install ssh keys
        run: |
           install -m 600 -D /dev/null ~/.ssh/id_rsa
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
           
      - name: copy compose.yml by scp 
        run: scp compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~
        
      - name: restart service
        run: >
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 
            "cd /home/${{ secrets.SSH_USER }} && 
            echo ${{ secrets.BOT_TOKEN }} > .env && 
            docker compose pull  && 
            docker-compose up -d --force-recreate --remove-orphans && 
            exit"

      
