
name: CI-CD-Docker-Bot
env:
  PROJECT_NAME: "training_tracker_bot"

on:
  push:
    branches:
      - main

jobs:
   Building_Docker_container:
      runs-on: ubuntu-latest
      steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set new version 
        run: |
          echo $(( $(<version.txt) + 1 )) > version.txt
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
          echo "New version: $VERSION"
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push 
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/{{ env.PROJECT_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/{{ env.PROJECT_NAME }}:{{ env.VERSION }}


      
